import pandas as pd

# 1. Load the datasets generated by our previous script
crm = pd.read_csv('crm_data.csv')
support = pd.read_csv('support_data.csv')
usage = pd.read_csv('usage_data.csv')

# 2. Aggregating Support Data
# We want the average sentiment per customer since one customer can have multiple tickets
support_agg = support.groupby('customer_name').agg({
    'sentiment_score': 'mean',
    'complexity_score': 'mean'
}).reset_index()

# 3. The "Revenue Bridge" Join
# Merging Sales, Support, and Product Usage into one Master Table
df = pd.merge(crm, usage, on='customer_name')
df = pd.merge(df, support_agg, on='customer_name', how='left')

# Fill customers with no tickets with a neutral sentiment (3.0)
df['sentiment_score'] = df['sentiment_score'].fillna(3.0)

# 4. Calculating the Health Score (Logic-based)
# We weight Engagement (40%), Sentiment (30%), and Adoption (30%)
def calculate_health(row):
    # Engagement: Inverse of last login (lower days = higher score)
    engagement = max(0, 100 - (row['last_login_days_ago'] * 3))
    
    # Sentiment: Scale 1-5 to 0-100
    sentiment = row['sentiment_score'] * 20
    
    # Adoption: Scale 0-1 to 0-100
    adoption = row['feature_adoption_rate'] * 100
    
    return (engagement * 0.4) + (sentiment * 0.3) + (adoption * 0.3)

df['health_score'] = df.apply(calculate_health, axis=1)

# 5. Identifying "Revenue at Risk" (The Executive Filter)
# Filter: High Value (>$5k MRR) AND Low Health (<50)
at_risk = df[(df['mrr'] > 5000) & (df['health_score'] < 50)].sort_values(by='mrr', ascending=False)

# 6. Final Report Output
print("--- STRATEGIC REVENUE RISK REPORT ---")
print(f"Total Customers Analyzed: {len(df)}")
print(f"Accounts identified as 'At Risk': {len(at_risk)}")
print(f"Total Revenue at Risk: ${at_risk['mrr'].sum():,.2f}")
print("\nTop 5 High-Priority Interventions:")
print(at_risk[['customer_name', 'tier', 'mrr', 'health_score']].head())

# Save for documentation
at_risk.to_csv('high_priority_risk_report.csv', index=False)
